tmc_trade/apps/auth_users/urls.py
from django.urls import path,include
from apps.auth_users import views

app_name = "auth_users"

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

tmc_trade/apps/tutorial/urls.py
from django.urls import path,include
from apps.tutorial import views

app_name = "tutorial"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('tutorial/', views.tutorial, name='tutorial'),
    path('tutorial_details/', views.tutorial_details, name='tutorial_details'),
    
]

tmc_trade/tmc_trade/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.auth_users.urls")),
    path('', include("apps.tutorial.urls")),
]

tmc_trade/apps/auth_users/models.py
from django.db import models

# Create your models here.

tmc_trade/apps/tutorial/models.py
from django.db import models

# Create your models here.

tmc_trade/apps/auth_users/views.py
from django.http import HttpResponse
from django.shortcuts import render



def home(request):
    return render(request, 'auth_users/home_page.html')

def register(request):
    return render(request, 'auth_users/register.html')

def login(request):
    return render(request, 'auth_users/login.html')

def logout(request):
    return render(request, 'auth_users/home_page.html')

def profile(request):
    return render(request, 'auth_users/profile.html')

tmc_trade/apps/tutorial/views.py
from django.http import HttpResponse
from django.shortcuts import render



def home(request):
    return HttpResponse( 'This is Tutorial Page')

def index(request):
    return render(request, 'index.html')

def tutorial(request):
    return render(request, 'tutorial/tutorial.html')

def tutorial_details(request):
    return render(request, 'tutorial/tutorial_details.html')

tmc_trade/apps/auth_users/templates/auth_users/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vensco</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
        <div class="container-fluid">
          <a class="navbar-brand h1 px-5  text-light" href="">TMC TRADE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
              <li class="nav-item me-2">
                <a class="nav-link active  text-light" aria-current="page" href="{% url 'auth_users:home' %}">Home</a>
              </li>
              
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'auth_users:profile' %}">Profile</a>
              </li>
  
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'tutorial:tutorial' %}">Tutorial</a>
              </li>
  
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'tutorial:tutorial_details' %}">Sections</a>
              </li>
      
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'auth_users:home' %}">Logout</a>
              </li>
         
              <li class="nav-item me-2 ">
                <a class="nav-link  text-light" href="{% url 'auth_users:register' %}">Signup</a>
              </li>
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'auth_users:login' %}">Login</a>
              </li>
           
              <form class="d-flex mt-2" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-success" type="submit">Search</button>
              </form>
             
              
            </ul>
          </div>
        </div>
      </nav>
    
    <div class="display-5 text-center mb-4 mt-5">This is local home page</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

tmc_trade/apps/auth_users/templates/auth_users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vensco</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
        <div class="container-fluid">
          <a class="navbar-brand h1 px-5  text-light" href="">TMC TRADE</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
              <li class="nav-item me-2">
                <a class="nav-link active  text-light" aria-current="page" href="{% url 'auth_users:home' %}">Home</a>
              </li>
              
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'auth_users:profile' %}">Profile</a>
              </li>
  
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'tutorial:tutorial' %}">Tutorial</a>
              </li>
  
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'tutorial:tutorial_details' %}">Sections</a>
              </li>
      
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'auth_users:home' %}">Logout</a>
              </li>
         
              <li class="nav-item me-2 ">
                <a class="nav-link  text-light" href="{% url 'auth_users:register' %}">Signup</a>
              </li>
              <li class="nav-item me-2">
                <a class="nav-link  text-light" href="{% url 'auth_users:login' %}">Login</a>
              </li>
           
              <form class="d-flex mt-2" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-success" type="submit">Search</button>
              </form>
             
              
            </ul>
          </div>
        </div>
      </nav>
    <div class="display-5 text-center mb-4 mt-5">This is login page</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

tmc_trade/apps/auth_users/templates/auth_users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vensco</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body> 
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
    <div class="container-fluid">
      <a class="navbar-brand h1 px-5  text-light" href="">TMC TRADE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
          <li class="nav-item me-2">
            <a class="nav-link active  text-light" aria-current="page" href="{% url 'auth_users:home' %}">Home</a>
          </li>
          
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:profile' %}">Profile</a>
          </li>

          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'tutorial:tutorial' %}">Tutorial</a>
          </li>

          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'tutorial:tutorial_details' %}">Sections</a>
          </li>
  
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:home' %}">Logout</a>
          </li>
     
          <li class="nav-item me-2 ">
            <a class="nav-link  text-light" href="{% url 'auth_users:register' %}">Signup</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:login' %}">Login</a>
          </li>
       
          <form class="d-flex mt-2" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
          </form>
         
          
        </ul>
      </div>
    </div>
  </nav>
    <div class="display-5 text-center mb-4 mt-5">This is profile page</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

tmc_trade/apps/auth_users/templates/auth_users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vensco</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body> 
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
    <div class="container-fluid">
      <a class="navbar-brand h1 px-5  text-light" href="">TMC TRADE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
          <li class="nav-item me-2">
            <a class="nav-link active  text-light" aria-current="page" href="{% url 'auth_users:home' %}">Home</a>
          </li>
          
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:profile' %}">Profile</a>
          </li>

          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'tutorial:tutorial' %}">Tutorial</a>
          </li>

          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'tutorial:tutorial_details' %}">Sections</a>
          </li>
  
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:home' %}">Logout</a>
          </li>
     
          <li class="nav-item me-2 ">
            <a class="nav-link  text-light" href="{% url 'auth_users:register' %}">Signup</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:login' %}">Login</a>
          </li>
       
          <form class="d-flex mt-2" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
          </form>
         
          
        </ul>
      </div>
    </div>
  </nav>
    <div class="display-5 text-center mb-4 mt-5">This is register page</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

tmc_trade/apps/tutorial/templates/tutorial/tutorial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vensco</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
   
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
        <div class="container-fluid">
            <a class="navbar-brand h1 px-5 text-light" href="">TMC TRADE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
                    <li class="nav-item me-2">
                        <a class="nav-link active text-light" aria-current="page" href="{% url 'auth_users:home' %}">Home</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link text-light" href="{% url 'auth_users:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link text-light" href="{% url 'tutorial:tutorial' %}">Tutorial</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link text-light" href="{% url 'tutorial:tutorial_details' %}">Sections</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link text-light" href="{% url 'auth_users:home' %}">Logout</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link text-light" href="{% url 'auth_users:register' %}">Signup</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="nav-link text-light" href="{% url 'auth_users:login' %}">Login</a>
                    </li>
                    <form class="d-flex mt-2" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-success" type="submit">Search</button>
                    </form>
                </ul>
            </div>
        </div>
    </nav>

    <div class="display-5 text-center mb-4 mt-5">This is tutorial page</div>

    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

tmc_trade/apps/tutorial/templates/tutorial/tutorial_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vensco</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
     <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
    <div class="container-fluid">
      <a class="navbar-brand h1 px-5  text-light" href="">TMC TRADE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
          <li class="nav-item me-2">
            <a class="nav-link active  text-light" aria-current="page" href="{% url 'auth_users:home' %}">Home</a>
          </li>
          
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:profile' %}">Profile</a>
          </li>

          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'tutorial:tutorial' %}">Tutorial</a>
          </li>

          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'tutorial:tutorial_details' %}">Sections</a>
          </li>
  
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:home' %}">Logout</a>
          </li>
     
          <li class="nav-item me-2 ">
            <a class="nav-link  text-light" href="{% url 'auth_users:register' %}">Signup</a>
          </li>
          <li class="nav-item me-2">
            <a class="nav-link  text-light" href="{% url 'auth_users:login' %}">Login</a>
          </li>
       
          <form class="d-flex mt-2" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
          </form>
         
          
        </ul>
      </div>
    </div>
  </nav>
    <div class="display-5 text-center mb-4 mt-5">This is tutorial_details page</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</body>
</html>

tmc_trade/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    
    {% block link %}{% endblock link %} 


    <title>{% block title %}  {% endblock title %}</title>
</head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000157;">
      <div class="container-fluid">
        <a class="navbar-brand h1 px-5  text-light" href="">TMC TRADE</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-5">
            <li class="nav-item me-2">
              <a class="nav-link active  text-light" aria-current="page" href="{% url 'auth_users:home' %}">Home</a>
            </li>
            
            <li class="nav-item me-2">
              <a class="nav-link  text-light" href="{% url 'auth_users:profile' %}">Profile</a>
            </li>

            <li class="nav-item me-2">
              <a class="nav-link  text-light" href="{% url 'tutorial:tutorial' %}">Tutorial</a>
            </li>

            <li class="nav-item me-2">
              <a class="nav-link  text-light" href="{% url 'tutorial:tutorial_details' %}">Sections</a>
            </li>
    
            <li class="nav-item me-2">
              <a class="nav-link  text-light" href="{% url 'auth_users:home' %}">Logout</a>
            </li>
       
            <li class="nav-item me-2 ">
              <a class="nav-link  text-light" href="{% url 'auth_users:register' %}">Signup</a>
            </li>
            <li class="nav-item me-2">
              <a class="nav-link  text-light" href="{% url 'auth_users:login' %}">Login</a>
            </li>
         
            <form class="d-flex mt-2" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-success" type="submit">Search</button>
            </form>
           
            
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}  {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
  
    {% block script %}{% endblock script %}
  </body>
</html>

tmc_trade/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block link %}{% endblock link %}

{% block title %}{% endblock title %}


{% block content %}

<div class="display-5 text-center mb-4 mt-5">This is global home page</div>

{% endblock content %}
   
{% block script %}{% endblock script %}